spring:
  application:
    name: 34_Web_MVC_Registration_form_DB_App

  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:test
    username: af
    password: af
    driver-class-name: org.h2.Driver


