spring:
  application:
    name: 20_SpringBoot_Data_JPA_MultipleRecords_App_1-2
    
  
  datasource:
    url: jdbc:mysql://database-1.cxum0ewmy035.ap-south-1.rds.amazonaws.com:3306/courses
    username: admin
    password: amjad321
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
     ddl-auto: update
    
    show-sql: true
        


